import React from "react";
import { Row, Col, Carousel, Badge } from "react-bootstrap";
import mm4e1 from "./meetinthemiddle1.jpg";
import mm4e2 from "./meetinthemiddle2.jpg";
import mm4e3 from "./meetinthemiddle3.jpg";

const MeetInTheMiddle4Equality = () => {
  return (
    <Row>
      <Col xs={12}>
        <h1>Meet in the Middle 4 Equality</h1>
        <p>
          <strong>Status:</strong> Past Event Site
        </p>
        <p>
          <strong>Technologies:</strong>{" "}
          <Badge className="group2">Joomla CMS</Badge>{" "}
          <Badge className="group9">Flash</Badge>{" "}
          <Badge className="group6">PHP</Badge>{" "}
          <Badge className="group6">SQL</Badge>{" "}
          <Badge className="group3">HTML</Badge>{" "}
          <Badge className="group3">CSS</Badge>{" "}
          <Badge className="group4">jQuery</Badge>{" "}
        </p>
        <div style={{ maxWidth: "700px" }} className="mb-3">
          <Carousel fade variant="dark" className="mb-3">
            <Carousel.Item>
              <img className="d-block w-100" src={mm4e1} alt="" />
            </Carousel.Item>
            <Carousel.Item>
              <img className="d-block w-100" src={mm4e2} alt="" />
            </Carousel.Item>
            <Carousel.Item>
              <img className="d-block w-100" src={mm4e3} alt="" />
            </Carousel.Item>
          </Carousel>
          <p>
            <small>
              <strong>Side 1:</strong> The Meet In The Middle 4 Equality home
              page is a Joomla CMS site featuring several categories on the home
              page. Prominent are the testimonials, event summary, featured
              articles, and organization endorsements sections.
            </small>
          </p>
          <p>
            <small>
              <strong>Slide 2:</strong> The core of this event focused site was
              gathering contact information to estimate the costs and advertise
              attendance to speakers and vendor sponsors. It also allowed us to
              help coordinate transportation and housing for the people who
              attended the event. Joomla allowed me to quickly build out this
              functionality and share the data with the event organizers.
            </small>
          </p>
          <p>
            <small>
              <strong>Slide 3:</strong> The Endorsements page was core to the
              event in order to show that the community was coming together in
              Central California for a common cause. Each endorsement "button"
              was dynamically generated by uploading the endorser's logo, name,
              and URL into the CMS. The template then dynamically built out this
              page with links to each.
            </small>
          </p>
        </div>
        <p>
          A Fresno local organization needed to develop a new web site to
          convince people from around the state to rally in Fresno. This site is
          a fundraising tool as well as a method of getting the word out.
        </p>
        <h3>Challenges</h3>
        <ul>
          <li>
            Unpaid volunteer work on an accelerated schedule to develop a site
            structure and graphic design based on existing flyer and logo
          </li>
          <li>Implement site utilizing Joomla, SlideShow Pro and Flash</li>
          <li>
            Develop an RSVP form using PHP, jQuery form validation and MySQL to
            gather, store, and manage the RSVP data
          </li>
          <li>
            Administer remote hosted web server to accommodate this high traffic
            site
          </li>
        </ul>
      </Col>
    </Row>
  );
};

export default MeetInTheMiddle4Equality;
